### ISSUE TITLE
Push() not working

### ISSUE THREAD

**Issue by That-pro** [Scientific-Guy/enhanced.db#1]
It is ok when i use normal `new Table()` constructor but when i use normal `db.push()`. It is not working and giving me error as `db.push()` is not a function! I kindly request to update it!

**Comment by That-pro** [comment]
And with that this is missing `db.set('something.something', 'something)` so that it will store as
`something = {something: 'something'}`
Whereas it stores the key as `something.something = 'something'

**Comment by scientific-dev** [comment]
Uhmm i found this error just now after u were saying so we will be updating it soon to v0.0.86 in future just select watching to repo we will be releasing it....

Or if you want further support:
Join our Discord Server: https://discord.gg/sfyNXZx

**Comment by scientific-dev** [comment]
So for those who is getting same error try to use `v0.0.90`
